### ISSUE TITLE
Some Thoughts

### ISSUE THREAD

**Issue by shellscape** [leonzalion/doiuse-email#2]
_(This is a seriously awesome package)_

I opened a fork here: https://github.com/shellscape/doiuse-email. The biggest change there is that I swapped out the build system with `tsup` and changed up the `tsconfig` because I wasn't using your build and the tsconfig that came with it (there wasn't anything wrong with it, but) because I needed CJS compat in the package. `tsup` takes care of that _nicely_. 

I always wanted to show off what I was doing with it on https://github.com/shellscape/jsx-email:

<img width="524" alt="Group 20" src="https://github.com/leondreamed/doiuse-email/assets/76371/97fd0adb-c21a-4d9b-a74f-afa54120a728">

<img width="524" alt="Group 21" src="https://github.com/leondreamed/doiuse-email/assets/76371/af83f73a-36b6-4961-aa60-a40a8e00f980">

What do you think it would take to output an object for `errors`, `warnings`, and `notes` that more closely represented that visual structure; where for a single document, there was only one error (etc) message which pointed to an array of unique clients that are affected? I'm doing some `reduce` and `Set` shenanigans to make that happen as a consumer, but it would be cool for first class support.

Also saw your comment that you're not really using this anymore, so no worries if you don't want to put the time into it for the above - not at all expecting you to - but some direction on where to implement that would be cool if you're not into working on this again. I haven't looked at the source in depth yet, so pointers would be super helpful. 

Thanks again!

**Comment by leonsilicon** [comment]
haha it's been a while since i wrote this code, but it seems like you'd probably have to modify the methods in the `DoIUseEmail` class https://github.com/leondreamed/doiuse-email/blob/main/src/utils/doiuse.ts) to accept a specific email client as a parameter (right now they all either loop over `this.emailClients` or append to the `errors`/`warnings` array indiscriminately).

jsx-email looks super cool! i remember i created this package back when i was trying to write emails using code (i used something called maizzle) but writing emails in raw email-XML was just too painful so i ended up using SaaS email builders instead 😅)

i probably won't have time to do any major refactors or add new features to this package, so i'd be happy to transfer the repo and/or package name to you if you want :)

(also apologies in advance if the source code is messy!)

**Comment by shellscape** [comment]
that would be _amazing_. thanks for being open to that, totally down for taking the reigns.

**Comment by leonsilicon** [comment]
i've invited you to the npm package as a collaborator, but i think GitHub needs you to rename your existing fork for a repo transfer:
<img width="737" alt="image" src="https://github.com/leondreamed/doiuse-email/assets/36966635/786f7315-5820-4f73-b0f5-76c2fadeb312">

and honestly it's an honor to have one of my packages adopted by a legend in the open-source community 😉

**Comment by shellscape** [comment]
no worries, just renamed it. and man, thanks for the compliments.

**Comment by leonsilicon** [comment]
hm it seems like you might need to delete the fork altogether first:
<img width="755" alt="image" src="https://github.com/leondreamed/doiuse-email/assets/36966635/34209f8a-b517-47bf-879e-300bfb863efe">

**Comment by shellscape** [comment]
Done!
